# Generated by Django 5.2.1 on 2025-06-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hr_document',
            field=models.FileField(blank=True, null=True, upload_to='hr_documents/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HRIO', 'Health Records Information Officer'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('ICT', 'ICT Staff'), ('HOD', 'Head of Department'), ('ADMIN', 'System Administrator'), ('AUDITOR', 'Auditor'), ('RESEARCHER', 'Researcher')], max_length=20),
        ),
    ]
