# Generated by Django 5.2.1 on 2025-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_hr_document_researcherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facility',
            field=models.CharField(blank=True, choices=[('FAC1', 'Main Hospital'), ('FAC2', 'Regional Clinic')], max_length=50, null=True),
        ),
    ]
