# Generated by Django 5.2.1 on 2025-06-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
    ]
