# Generated by Django 5.2.1 on 2025-05-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='id',
        ),
        migrations.AlterField(
            model_name='consent',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='requests.datarequest'),
        ),
    ]
